main/urls.py
from django.urls import path
from . import views

app_name = "main"   


urlpatterns = [
    path("", views.import_ocel, name="import_ocel"),
    path("import_ocel", views.import_ocel, name="import_ocel"),
    path("upload", views.upload_data, name="upload"),
    path("view_ocel/", views.view_ocel, name="view_ocel"),
    path("view_ocel/<int:selected_ocel_id>", views.view_ocel, name="view_ocel"),
    path("view/", views.view_pm, name="view"),
    path("view/<int:selected_ocel_id>/<str:pm_style>/<str:format>", views.view_pm, name="view"),
    path("docs", views.docs, name="docs"),
]

ui4pm4py/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from ui4pm4py import graph_view_app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('sap_python.urls')),
    url('', include('django_plotly_dash.urls')),
]

main/models.py
from django.db import models
from django.utils.dateparse import parse_date
import pandas as pd
# Create your models here.

class PandaDFModel(models.Model):
    class Meta:
        abstract = True

    # Convert django model back to pd.dataframe
    @classmethod
    def as_dataframe(cls, queryset=None, field_list=None, df_column_names = None):
        if queryset is None:
            queryset = cls.objects.all()
        if field_list is None:
            field_list = [_field.name for _field in cls._meta._get_fields(reverse=False)]

        data = []
        [data.append([obj.serializable_value(column) for column in field_list]) for obj in queryset]

        columns = df_column_names if (df_column_names) else field_list

        df = pd.DataFrame(data, columns=columns)
        return df

class SAPImport(models.Model):
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)
    ocel_name = models.CharField(max_length=100, default="my_ocel_name")

class OCEL_entry(PandaDFModel):
    ocel_eid = models.CharField(db_column="ocel:eid", default = "-1", max_length=255)
    ocel_activity = models.CharField(db_column="ocel:activity", default = "no activity provided", max_length=255)
    ocel_timestamp = models.DateTimeField(db_column = "ocel:timestamp", default=parse_date("2000-01-01"))
    ocel_oid = models.CharField(db_column = "ocel:oid", default = "No oid provided", max_length=255)
    ocel_type = models.CharField(db_column = "ocel:type", default = "No type provided",max_length=255)
    parent_ocel = models.ForeignKey('main.OCEL', on_delete=models.CASCADE,  db_column = "parent_ocel", default = "NoParent")   #What ocel does this entry belong to?

class OCEL(PandaDFModel):
    name = models.CharField(default = "myOCEL", max_length = 100)
    def __str__(self):
        return str(self.id) + " - " + self.name

class PMType(models.Model):
    generate_PN = models.BooleanField(default=True)
    generate_DFG = models.BooleanField(default=True)

class SelectedPM(models.Model):
    ocel_id = models.ForeignKey('main.OCEL', on_delete=models.CASCADE,  db_column = "ocel_id", default = "error")
    pm_style = models.CharField(default = "PN", max_length=8)
    format = models.CharField(default = "PNG", max_length=8)

class CytoscapePM(models.Model):
    ocel_id = models.ForeignKey('main.OCEL', on_delete=models.CASCADE,  db_column = "ocel_id", default = "error")
    cytoscape_pm_json = models.JSONField(null=True, blank=True)
    pm_style = models.CharField(default = "PN", max_length=8)

main/forms.py
from django import forms
from .models import OCEL
from os.path import splitext
# Create your models here.


class SAPImportForm(forms.Form):
    ocel_name = forms.CharField(label='OCEL Name')
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

class OCELModelSelectorForm(forms.Form):
    CHOICES = [("PN", "Petri Net"), ("DFG", "Directly Follows Graph"),]
    model_style = forms.ChoiceField(widget = forms.RadioSelect,choices=CHOICES, initial="PN")
    format = forms.ChoiceField(widget= forms.RadioSelect,choices=[("PNG", "Static Image"), ("CYTO", "Interactive Graph")], initial="CYTO")
    ocel = forms.ModelChoiceField(queryset=OCEL.objects.all(), widget = forms.Select(attrs = {'class':"OCEL-select", 'onchange': "SelectOCEL(this.value);"}), label="OCEL")

class OCELUploadForm(forms.Form):
    ocel_name = forms.CharField(label='OCEL Name')
    ocel_file = forms.FileField(label = 'OCEL File', widget = forms.FileInput(attrs = {'type': 'file', 'class':'form-control', 'required': True, }))

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
try:
    from pyrfc import LogonError, CommunicationError
except ImportError:
    print("You do not have pyrfc installed! You can not use the SAP Connector functionality!")
from .forms import OCELModelSelectorForm, SAPImportForm, OCELUploadForm
from django.contrib import messages
from .utils import *
from .models import OCEL, SelectedPM
from sap_python import main
from pm4py import read_ocel
from django.core.files.storage import FileSystemStorage


# Create your views here.
def import_ocel(request):
    if request.method == 'POST':
        form = None
        if request.POST['button'] == "sap_confirm":
            form = SAPImportForm(request.POST)
            if form.is_valid():
                cleaned_form = form.cleaned_data
                try:
                    new_id = save_df_ocel_to_django_model(main.get_relations(cleaned_form["username"], cleaned_form["password"]), cleaned_form["ocel_name"])
                    return HttpResponseRedirect('/view_ocel/' + str(new_id))
                except CommunicationError:
                    messages.error(request, "Could not connect to server! Make sure your IP address is activated: https://remotelogin.sapucc.in.tum.de/")
                except LogonError:
                    messages.error(request, "Could not log you in, please check login credentials!")
                except Exception as e:
                    messages.error(request, e) 
                return HttpResponseRedirect('/import_ocel')
        
        elif request.POST['button'] == "upload_confirm":
            form = OCELUploadForm(request.POST, request.FILES)
            if form.is_valid():
                new_id = ""
                cleaned_form = form.cleaned_data
                upload_file = cleaned_form["ocel_file"]
                name = cleaned_form["ocel_name"]
                try:
                    fs = FileSystemStorage()
                    fs.save(upload_file.name, upload_file)
                    print("saved: ", name) 
                    ocel = read_ocel(fs.path(upload_file.name))
                    new_id = str(save_df_ocel_to_django_model(ocel.relations, name))
                    fs.delete(fs.path(upload_file.name))
                    return HttpResponseRedirect('/view_ocel/' + new_id)
                except Exception as e:
                    messages.error(request, e)
                finally:
                    fs.delete(fs.path(upload_file.name))            
        return HttpResponseRedirect('/import_ocel')
    else:
        sap_form = SAPImportForm()
        upload_form = OCELUploadForm()
        return render(request, "main/import_ocel.html", {'sap_form': sap_form, 'upload_form': upload_form})

def upload_data(request):
    if request.method == "POST":
        form = OCELUploadForm(request.POST, request.FILES)
        if form.is_valid():
            new_id = ""
            cleaned_form = form.cleaned_data
            upload_file = cleaned_form["ocel_file"]
            name = cleaned_form["ocel_name"]
            try:
                fs = FileSystemStorage()
                fs.save(upload_file.name, upload_file)
                print("saved: ", name)
                ocel = read_ocel(fs.path(upload_file.name))
                new_id = str(save_df_ocel_to_django_model(ocel.relations, name))
                fs.delete(fs.path(upload_file.name))
                return HttpResponseRedirect('/view_ocel/' + new_id)
            except Exception as e:
                messages.error(e)                
            return HttpResponseRedirect('/upload/' + new_id)
    else:
        form = OCELUploadForm()
    return render(request = request, template_name = "main/upload.html", context = {'form': form})

def view_ocel(request, selected_ocel_id = -1):
    # Received results of form (OCEL Model Selector)
    if request.method == 'POST':

        if request.POST['button'] == "discover":
            form = OCELModelSelectorForm(request.POST)
            if form.is_valid():
                cleaned_form = form.cleaned_data
                ocel_id = get_id_from_id_name(str(cleaned_form["ocel"]))
                style = cleaned_form["model_style"]
                format = cleaned_form["format"]
                return HttpResponseRedirect('/view/' + str(ocel_id) + "/" + style + "/" + format)

        elif request.POST['button'] == "delete":
            ocelid = request.POST['ocel']
            delete_ocel(ocelid)
            return HttpResponseRedirect('/view_ocel/')
        

    ocel_df = get_all_ocel_entries_as_string_df()
    columns = [{'field': f, 'title': f} for f in ocel_df.columns]
    ocel_data_json = ocel_df.to_json(orient='records')
    context = {
        "ModelSelectorForm": OCELModelSelectorForm(),
        "data": ocel_data_json,
        "columns" : columns, 
        "selectedOCEL": selected_ocel_id,
    }    
    return render(request = request, template_name = "main/view_ocel.html", context=context)

def view_pm(request, selected_ocel_id = -1, pm_style = "", format = ""):
    if selected_ocel_id not in get_ocel_id_name_dict().keys() or pm_style not in ["PN", "DFG"] or format not in ["PNG", "CYTO"]:
        return HttpResponseRedirect('/view_ocel/')
    if pm_style == "DFG" and format == "CYTO":
        return HttpResponseRedirect("/view/" + str(selected_ocel_id) +"/" + pm_style + "/" + "PNG")
    SelectedPM.objects.all().delete()
    selection = SelectedPM(ocel_id = OCEL.objects.filter(id = selected_ocel_id).first(), pm_style = pm_style, format = format)
    selection.save()
    return render(request,'main/view.html')

def docs(request):
    return render(request = request, template_name = "main/docs.html")

main/templates/main/docs.html
<!-- home / about page with general info -->
<!DOCTYPE html>
<html lang = "en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <!-- Responsive Meta Tag: used for scaling on mobile, possibly not wanted here -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>PM4P2P</title>
    {% load static %}
        <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <!-- Custom CSS -->
        <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">
        <link href="{% static 'css/mystyle.css' %}" rel="stylesheet">
        <link rel="shortcut icon" type="image/png" href="{% static 'img/clipboard2-data.svg' %}"/>
  </head>
  <body> 
    <div class="d-flex" id="wrapper">

      <div class="border-right" id="sidebar-wrapper">   
        {% include 'main/sidebar.html'%}
      </div>

        {% block content %}
        <header class="docs-header py-3 px-4">
            <h1 class="docs-heading">Getting Started with PM4P2P
            </h1>

            <section class="docs-intro">
                <p>In the main directory you can find the documentation of <b>PM4P2P</b> in the form of a <b>pdf</b>. It contains the following informations:
                </p>
                  <ol>
                    <li><b>Instalation</b></li>
                    <ul>
                        <li>
                          <i>Prerequisites</i>: What you need to install on your machine before starting the server 
                        </li>
                        <li>
                          <i>Setting up the server</i>: Setting up the virtual environment and installing the needed requirements 
                        </li>
                    </ul>
                    <li><b>Importing OCELs</b></li>
                      <ul>
                        <li>
                          <i>SAP OCELs:</i> How to import data directly from the SAP system
                        </li>
                        <li>
                          <i>External OCELs:</i> How to import your own data
                        </li>
                      </ul>
                    <li><b>Viewing and Managing Saved OCELs:</b></li> In which formats the generated models are displayed
                    
                  </ol>
            </section><!--//docs-intro-->
        </header>           
        {% endblock %}
  
      </div>
    <!-- JS imports, necessary for Bootstrap, order is relevant! -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/import_ocel.html
<!-- Import directly from SAP databases using hdbcli-->
<!DOCTYPE html>
<html lang = "en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <!-- Responsive Meta Tag: used for scaling on mobile, possibly not wanted here -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>PM4P2P</title>
    {% load static %}
        <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <!-- Custom CSS -->
        <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">
        <link href="{% static 'css/mystyle.css' %}" rel="stylesheet">
        <link rel="shortcut icon" type="image/png" href="{% static 'img/clipboard2-data.svg' %}"/>
  </head>
  <body> 
    <div class="d-flex" id="wrapper">
      <div class="border-right" id="sidebar-wrapper">   
        {% include 'main/sidebar.html'%}
      </div>
        {% block content %}
        <div class="container py-5 no-gutters">
          <div class = "col-lg-5 py-2 px-0">            
            {% load bootstrap4 %}
              <div class="card">
                <ul class="nav nav-tabs">
                  <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#import_from_sap">Retrieve Data from SAP</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#upload">Upload OCEL file</a>
                  </li>
                </ul>
                
                <div class="card-body">
                  <div class="tab-content">
                    <div role="tabpanel" class="tab-pane show active" id="import_from_sap">                                            
                      <form method="POST" action="">
                        {% csrf_token %}
                        {% bootstrap_form sap_form %}
                        <div class="alert alert-info">
                          <a class="close" href="#" data-dismiss="alert">x</a>
                          To create an object-centric event log from SAP data, please provide a name for the OCEL as well as your login credentials to SAP.
                      </div> 
                        {% for message in messages %}    
                      <div class="alert alert-danger">
                          <a class="close" href="#" data-dismiss="alert">×</a>
                            {{ message }}
                      </div> 
                      {% endfor %}                  
                        <div class="text-right">
                          <button type="submit" name = "button" value="sap_confirm" class="btn btn-primary" id="sap_confirm">Retrieve Data</button>
                        </div>
                      </form>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="upload">
                        <form action="" method="POST" enctype="multipart/form-data">
                          {% csrf_token %}
                          {% bootstrap_form upload_form %}
                          <div class="text-right">
                          <button type="submit" class="btn btn-primary" name = "button" value = "upload_confirm">Upload</button>
                          </div>
                        </form>
                    </div>
                  </div>
                </div>
              </div>            
          </div>
        </div>
        {% endblock %}
        
  
      </div>
    <!-- JS imports, necessary for Bootstrap, order is relevant! -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/sidebar.html
{% load static %}
<div class="list-group list-group-flush">
    {% url 'main:import_ocel' as home_url %}
    <a href="{{ home_url }}" class="sidebar-heading list-group-item list-group-item-action"><img style='height: 100%;object-fit: contain ' src="{% static 'img/clipboard2-data.svg' %}"/><b>PM4P2P</b></a>
    {% url 'main:import_ocel' as import_ocel %}
    <a href="{{import_ocel}}" class="list-group-item list-group-item-action {% if import_ocel in request.path %} active{% else %} bg-light{% endif %}">Import Data</a>
    {% url 'main:view_ocel' as view_ocel_url %}
    <a href="{{view_ocel_url}}" class="list-group-item list-group-item-action {%if view_ocel_url in request.path%} active{%endif%}">View OCEL</a>
    {% url 'main:view' as view_url %}
    <a href="{{view_url}}" class="list-group-item list-group-item-action {%if view_url in request.path%} active {%endif%}">View Process Model</a>
    {% url 'main:docs' as docs_url %}
    <a href="{{docs_url}}" class="list-group-item list-group-item-action {%if docs_url in request.path%} active {%endif%}">Documentation</a>
</div>

main/templates/main/view.html
<!-- View and manipulate (apply filters to) the process model -->
{%load plotly_dash%}
<!DOCTYPE html>
<html lang = "en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <!-- Responsive Meta Tag: used for scaling on mobile, possibly not wanted here -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>PM4P2P</title>
    {% load static %}
        <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <!-- Custom CSS -->
        <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">
        <link href="{% static 'css/mystyle.css' %}" rel="stylesheet">
        <link rel="shortcut icon" type="image/png" href="{% static 'img/clipboard2-data.svg' %}"/>
  </head>
  <body> 
    <div class="d-flex" id="wrapper">
      <div class="border-right" id="sidebar-wrapper">   
        {% include 'main/sidebar.html'%}
    </div>
      {% block content %}
        <div class="container py-5 px-5 row g-0">
          <div class="container col border border-0 px-0 mx-0">
            {% plotly_app name='graph_view' ratio=1 %}
          </div>
        </div>
        {% endblock %}
    </div>
    <!-- JS imports, necessary for Bootstrap, order is relevant! -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/view_ocel.html
<!-- View uploaded/imported data and generate process model (select DFG/PN) -->
<!-- Also provide download feature (JSON/XML) -->
<!DOCTYPE html>
<html lang = "en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <!-- Responsive Meta Tag: used for scaling on mobile, possibly not wanted here -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>PM4P2P</title>
    {% load static %}
        <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.21.2/dist/bootstrap-table.min.css">
    <link rel="stylesheet" href="https://kit-free.fontawesome.com/releases/latest/css/free.min.css">
        <!-- Custom CSS -->
        <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">
        <link href="{% static 'css/mystyle.css' %}" rel="stylesheet">
        <link rel="shortcut icon" type="image/png" href="{% static 'img/clipboard2-data.svg' %}"/>
  </head>
  <body> 
    <div class="d-flex" id="wrapper">
      <div class="border-right" id="sidebar-wrapper">   
        {% include 'main/sidebar.html'%}
      </div>
        {% block content %}
        {% load bootstrap4 %}
        <div class="row py-5 px-4">
              <div class="card border">
                <div class="card-header w-100 justify-content-between">
                  <form method="POST" action="" id = "ocel-model-selector">
                    {% csrf_token %}
                    {%bootstrap_form ModelSelectorForm%}
                    <div class="text-right">
                      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deletionModal" disabled id="discover-model-delete-modal">Delete OCEL</button>
                      <button type="submit" name="button" value="discover" class="btn btn-primary" disabled id="discover-model-submit">Discover Model</button>
                      <!-- Modal -->
                      <div class="modal fade" id="deletionModal" tabindex="-1" role="dialog" aria-labelledby="deletionModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="deletionModalLabel">Delete OCEL</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              Are you sure you want to delete this OCEL?
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                              <button type="submit" name="button" value="delete" class="btn btn-danger" id="delete-ocel-submit">Delete OCEL</button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>                
                 <!---possibly add last_updated data here-->
                </div>
                <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
                <div id = "toolbar">
                </div>                
                <table 
                id='datatable'
                data-toolbar = "#toolbar"
                data-show-toggle = "false"
                data-show-columns = "true"
                data-pagination = "true"
                data-page-size = 25
                striped = "true"
                >
                  </table>
                  <script>
                    $(function() {
                      $('#datatable').bootstrapTable({
                          data: [],
                          columns: {{columns |safe}},
                          search:true,
                      });
                      $('#datatable').bootstrapTable("hideColumn", "OCEL_id_name");                      
                      $('#id_ocel').val("{{selectedOCEL}}").trigger('change'); //select initial value (sometimes) specified from view.py (e.g. when there is only one OCEL)
                    });
                    function SelectOCEL(value){
                        selected_ocel = value;
                        if (!selected_ocel){
                          selected_ocel = "";
                        }
                        temp = {{data|safe}};
                        var parent_id = -1;
                        data_to_show = $.grep(temp, function (n,i){
                            parent_id = Number(n.OCEL_id_name.split(" ")[0]);
                            return parent_id == selected_ocel;
                          });
                        $('#datatable').bootstrapTable("load", data_to_show);
                        $('#discover-model-submit').attr('disabled', (selected_ocel == ""));
                        $('#discover-model-delete-modal').attr('disabled', (selected_ocel == ""));           
                      }                        
                  </script>
              </div>

        </div>
        {% endblock %}
        
    </div>
    <!-- JS imports, necessary for Bootstrap, order is relevant! -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.2/dist/bootstrap-table.min.js"></script>
  </body>
</html>